# lightweight container for go
FROM golang:1.17-alpine

# update container's packages and install git
RUN apk update && apk add --no-cache git

# set /app to be the active directory
WORKDIR /app

# copy all files from outside container, into the container
COPY . .

COPY ./data/config.yaml ./data/config.yaml

# download dependencies
RUN go mod tidy -compat="1.17"

# build binary
RUN go build -o dbo-backend-oviek

# set the entry point of the binary
ENTRYPOINT ["/app/dbo-backend-oviek"]
